# Preparation of Dataset (development notebook)

## Import section

In [1]:
import numpy as np
import pandas as pd

from etnn.data.prepare_ferris_wheel import prepare_1_ferris, generate_ferris_dataset, add_valid_permutations
from etnn.data.ferris_score_helpers import build_wheel_happyness
from etnn.data.ferris_wheel import load_pure_ferris_wheel_dataset, load_modified_ferris_wheel_dataset
import torch
from torch.utils.data import random_split, DataLoader
from tqdm import tqdm

In [2]:
DATASET_PATH = "../datasets"

## Person dataset

In [3]:
df_health = prepare_1_ferris(
    dataset_path="../datasets",
    df_name_output="health_dataset_preprocessed-1.csv",
    df_name_input="Sleep_health_and_lifestyle_dataset.csv",
    try_pregen=True
)

In [4]:
df_health.head()

id  age  occupation  sleep_duration  sleep_quality  physical_activity  \
0   1   27           1             6.1              6                 42   
1   2   28           2             6.2              6                 60   
2   3   28           2             6.2              6                 60   
3   4   28           3             5.9              4                 30   
4   5   28           3             5.9              4                 30   

   stress_level  bmi  heart_rate  daily_steps  sleep_disorder  \
0             6    2          77         4200               0   
1             8    0          75        10000               0   
2             8    0          75        10000               0   
3             8    3          85         3000               1   
4             8    3          85         3000               1   

   blood_pressure1  blood_pressure2  gender_male  gender_female  gender_other  
0              126               83         True          False         False  
1              125               80         True          False         False  
2              125               80         True          False         False  
3              140               90         True          False         False  
4              140               90         True          False         False

## Gondola dataset (indexing)

In [5]:
# take group of ids from persons and state how the label for this group shall be calculated

In [6]:
# define ferris wheel
num_gondolas = 10
num_part_pg = 5

In [7]:
# generate sample element
random_order = np.arange(len(df_health)) + 1
np.random.shuffle(random_order)

In [8]:
example = [
    random_order[i*num_part_pg:(i+1)*num_part_pg]
    for i in range(num_gondolas)
]

In [9]:
example

[array([192, 282, 283, 292, 191]),
 array([287, 117, 303, 254, 233]),
 array([316, 354,  85, 297,  81]),
 array([361, 326, 197,  76,  21]),
 array([187, 185,  71, 360,   6]),
 array([245, 320, 302, 256, 352]),
 array([143, 156,   5,  24, 137]),
 array([371, 176,  47,   8, 362]),
 array([ 44, 224, 172, 328, 135]),
 array([ 51,  28, 166, 270, 247])]

In [10]:
random_order[:num_gondolas*num_part_pg].reshape(num_gondolas, num_part_pg)

array([[192, 282, 283, 292, 191],
       [287, 117, 303, 254, 233],
       [316, 354,  85, 297,  81],
       [361, 326, 197,  76,  21],
       [187, 185,  71, 360,   6],
       [245, 320, 302, 256, 352],
       [143, 156,   5,  24, 137],
       [371, 176,  47,   8, 362],
       [ 44, 224, 172, 328, 135],
       [ 51,  28, 166, 270, 247]])

Rules:
- People being happy with other people in same gondola
    + Age composition too seperated is bad
    + shift in gender is bad if too much, 50-50 is good or all one gender
    + same with age composition
    + sleep derived(multiplier with quality) persons get a subtraction and 'good sleepers' get bonus (sleep disorder counts as stronger subtraction)
    + higher heart rate and pressure = joy or fear
    + composition of persons in regards to bmi : extreme values make others (no exception for group all those as to many underweight or overweight persons may be awquard as well)
- People being happy with neighboring gondolas composition
    + same age gets bonus, none gets penalty as potentially group is separated
    + gap between happyness index between self and neighbors causes it to produce a mean of only the neighbors

In [11]:
build_wheel_happyness(df_health, example)

57.93382666666667

In [12]:
build_wheel_happyness(df_health, random_order[:num_gondolas * num_part_pg].reshape(num_gondolas, num_part_pg))

57.93382666666667

In [13]:
# define dataset size
num_to_generate = 10_000
# define ferris wheel
num_gondolas = 10
num_part_pg = 5

In [14]:
df_index, df_health = generate_ferris_dataset(
    num_gondolas=num_gondolas,
    num_part_pg=num_part_pg,
    num_to_generate=num_to_generate,
    dataset_path="../datasets",
    df_intermediate_output_name="health_dataset_preprocessed-1.csv",
    df_name_input="Sleep_health_and_lifestyle_dataset.csv",
    try_pregen=True
)

In [15]:
df_index.head()

g-0_p-0  g-0_p-1  g-0_p-2  g-0_p-3  g-0_p-4  g-1_p-0  g-1_p-1  g-1_p-2  \
0      264      191       98      235       35      356      253        9   
1      338      176       95       11      161      248      364       53   
2      290       99       75       21      237      287      215      213   
3       15      277       93      106      290      354       60      226   
4      190      260       34      286      360      167      251      298   

   g-1_p-3  g-1_p-4  ...  g-8_p-1  g-8_p-2  g-8_p-3  g-8_p-4  g-9_p-0  \
0      147      311  ...      315      265       92       23      287   
1       64       71  ...      181      365       96      187      165   
2      172      214  ...       76      188      274       77      264   
3       75      318  ...      243      288       74      131      344   
4      256       15  ...       48      258      107        5      307   

   g-9_p-1  g-9_p-2  g-9_p-3  g-9_p-4      label  
0       17      234      223      117  68.011480  
1       38      114       98       56  55.463373  
2      117      254      168       65  66.108493  
3       86      266      218       83  58.642507  
4      121      162        7       37  62.584213  

[5 rows x 51 columns]

In [16]:
df_health.head()

id  age  occupation  sleep_duration  sleep_quality  physical_activity  \
0   1   27           1             6.1              6                 42   
1   2   28           2             6.2              6                 60   
2   3   28           2             6.2              6                 60   
3   4   28           3             5.9              4                 30   
4   5   28           3             5.9              4                 30   

   stress_level  bmi  heart_rate  daily_steps  sleep_disorder  \
0             6    2          77         4200               0   
1             8    0          75        10000               0   
2             8    0          75        10000               0   
3             8    3          85         3000               1   
4             8    3          85         3000               1   

   blood_pressure1  blood_pressure2  gender_male  gender_female  gender_other  
0              126               83         True          False         False  
1              125               80         True          False         False  
2              125               80         True          False         False  
3              140               90         True          False         False  
4              140               90         True          False         False

In [17]:
df_index.iloc[:, :-1]

g-0_p-0  g-0_p-1  g-0_p-2  g-0_p-3  g-0_p-4  g-1_p-0  g-1_p-1  g-1_p-2  \
0         264      191       98      235       35      356      253        9   
1         338      176       95       11      161      248      364       53   
2         290       99       75       21      237      287      215      213   
3          15      277       93      106      290      354       60      226   
4         190      260       34      286      360      167      251      298   
...       ...      ...      ...      ...      ...      ...      ...      ...   
9995      127       84      110      152      265       90      318       72   
9996      286       97      191      288       32      268       41      347   
9997      372      168      198      199      239      369      323      277   
9998      154      310      224       59       87      207       97       78   
9999      351       31      277      304      357       35      111      254   

      g-1_p-3  g-1_p-4  ...  g-8_p-0  g-8_p-1  g-8_p-2  g-8_p-3  g-8_p-4  \
0         147      311  ...      299      315      265       92       23   
1          64       71  ...      100      181      365       96      187   
2         172      214  ...      122       76      188      274       77   
3          75      318  ...      235      243      288       74      131   
4         256       15  ...       28       48      258      107        5   
...       ...      ...  ...      ...      ...      ...      ...      ...   
9995      331      237  ...      346        7      341      126       70   
9996      272      169  ...      194      178      269      310       79   
9997      174      281  ...      191      112       75      331      177   
9998      290      241  ...       12      338      254      183      145   
9999       40       69  ...       16       71       65      163      296   

      g-9_p-0  g-9_p-1  g-9_p-2  g-9_p-3  g-9_p-4  
0         287       17      234      223      117  
1         165       38      114       98       56  
2         264      117      254      168       65  
3         344       86      266      218       83  
4         307      121      162        7       37  
...       ...      ...      ...      ...      ...  
9995      208       67      248      291      246  
9996      370      108      189      340       24  
9997      163      155        7      188      290  
9998       22       95      247      158      231  
9999      123      363      180      148      297  

[10000 rows x 50 columns]

## Total dataset creation

In [18]:
dataset = load_pure_ferris_wheel_dataset(
    num_gondolas=num_gondolas,
    num_part_pg=num_part_pg,
    num_to_generate=num_to_generate,
    dataset_path="../datasets",
    df_intermediate_output_name="health_dataset_preprocessed-1.csv",
    df_name_input="Sleep_health_and_lifestyle_dataset.csv",
    try_pregen=True
)

In [19]:
dataset[0]

(tensor([[4.5000e+01, 1.1000e+01, 6.9000e+00, 7.0000e+00, 5.5000e+01, 5.0000e+00,
          2.0000e+00, 7.5000e+01, 5.5000e+03, 0.0000e+00, 1.2500e+02, 8.2000e+01,
          0.0000e+00, 1.0000e+00, 0.0000e+00],
         [4.3000e+01, 4.0000e+00, 6.7000e+00, 7.0000e+00, 4.5000e+01, 4.0000e+00,
          2.0000e+00, 6.5000e+01, 6.0000e+03, 2.0000e+00, 1.3500e+02, 9.0000e+01,
          0.0000e+00, 1.0000e+00, 0.0000e+00],
         [3.6000e+01, 7.0000e+00, 7.1000e+00, 8.0000e+00, 6.0000e+01, 4.0000e+00,
          0.0000e+00, 6.8000e+01, 7.0000e+03, 0.0000e+00, 1.1500e+02, 7.5000e+01,
          0.0000e+00, 1.0000e+00, 0.0000e+00],
         [4.4000e+01, 4.0000e+00, 6.6000e+00, 7.0000e+00, 4.5000e+01, 4.0000e+00,
          2.0000e+00, 6.5000e+01, 6.0000e+03, 2.0000e+00, 1.3500e+02, 9.0000e+01,
          0.0000e+00, 1.0000e+00, 0.0000e+00],
         [3.1000e+01, 2.0000e+00, 7.7000e+00, 7.0000e+00, 7.5000e+01, 6.0000e+00,
          0.0000e+00, 7.0000e+01, 8.0000e+03, 0.0000e+00, 1.2000e+02, 8.00

## DataLoaders

In [20]:
generator = torch.Generator().manual_seed(420)
train_ds, val_ds, test_ds = random_split(dataset, [0.7, 0.1, 0.2], generator=generator)

In [21]:
train_ds

In [22]:
train_loader = DataLoader(train_ds, batch_size=32, shuffle=True)

In [23]:
for x, y in train_loader:
    print(f"x-shape:{x.shape}, y-shape:{y.shape}")
    break

x-shape:torch.Size([32, 50, 15]), y-shape:torch.Size([32])


## Specialize pure datasets

In [24]:
df_added_valid = add_valid_permutations(
    num_to_generate,
    df_index,
    num_gondolas
)

100%|██████████| 10000/10000 [00:00<00:00, 79905.66it/s]


In [25]:
df_added_valid

g-0_p-0  g-0_p-1  g-0_p-2  g-0_p-3  g-0_p-4  g-1_p-0  g-1_p-1  g-1_p-2  \
0        264.0    191.0     98.0    235.0     35.0    356.0    253.0      9.0   
1        338.0    176.0     95.0     11.0    161.0    248.0    364.0     53.0   
2        290.0     99.0     75.0     21.0    237.0    287.0    215.0    213.0   
3         15.0    277.0     93.0    106.0    290.0    354.0     60.0    226.0   
4        190.0    260.0     34.0    286.0    360.0    167.0    251.0    298.0   
...        ...      ...      ...      ...      ...      ...      ...      ...   
19995     44.0     43.0     87.0     17.0    230.0    311.0    260.0    221.0   
19996     52.0     87.0     12.0    184.0    151.0    168.0    236.0     89.0   
19997     35.0    338.0     28.0     87.0    232.0     40.0    234.0    285.0   
19998    191.0     92.0      1.0    204.0    209.0    111.0      9.0    136.0   
19999    307.0     17.0    256.0    261.0     65.0    357.0    365.0    363.0   

       g-1_p-3  g-1_p-4  ...  g-8_p-1  g-8_p-2  g-8_p-3  g-8_p-4  g-9_p-0  \
0        147.0    311.0  ...    315.0    265.0     92.0     23.0    287.0   
1         64.0     71.0  ...    181.0    365.0     96.0    187.0    165.0   
2        172.0    214.0  ...     76.0    188.0    274.0     77.0    264.0   
3         75.0    318.0  ...    243.0    288.0     74.0    131.0    344.0   
4        256.0     15.0  ...     48.0    258.0    107.0      5.0    307.0   
...        ...      ...  ...      ...      ...      ...      ...      ...   
19995    142.0    207.0  ...    251.0    339.0    341.0    304.0    192.0   
19996    279.0     61.0  ...      3.0     10.0    101.0    288.0    311.0   
19997     94.0    227.0  ...     18.0    231.0    372.0     26.0      4.0   
19998     80.0    351.0  ...    373.0    341.0    270.0    161.0     35.0   
19999    274.0    295.0  ...    170.0    117.0    277.0    101.0    241.0   

       g-9_p-1  g-9_p-2  g-9_p-3  g-9_p-4      label  
0         17.0    234.0    223.0    117.0  68.011480  
1         38.0    114.0     98.0     56.0  55.463373  
2        117.0    254.0    168.0     65.0  66.108493  
3         86.0    266.0    218.0     83.0  58.642507  
4        121.0    162.0      7.0     37.0  62.584213  
...        ...      ...      ...      ...        ...  
19995    130.0    355.0     99.0    111.0  67.306093  
19996     69.0     28.0    228.0    118.0  64.498840  
19997    255.0    317.0    213.0    298.0  65.748787  
19998    318.0    119.0    160.0      4.0  61.697907  
19999    338.0    223.0    161.0    220.0  59.530067  

[20000 rows x 51 columns]

In [26]:
dataset = load_modified_ferris_wheel_dataset(
    num_gondolas=num_gondolas,
    num_part_pg=num_part_pg,
    num_to_generate=num_to_generate,
    num_valid_to_add=num_to_generate,
    dataset_path="../datasets",
    df_intermediate_output_name="health_dataset_preprocessed-1.csv",
    df_name_input="Sleep_health_and_lifestyle_dataset.csv",
    try_pregen=True
)

## Change regression task to classification

In [27]:
temp = df_index.label/(10*num_gondolas)*10

In [28]:
temp.round()

0       7.0
1       6.0
2       7.0
3       6.0
4       6.0
       ... 
9995    6.0
9996    6.0
9997    7.0
9998    7.0
9999    5.0
Name: label, Length: 10000, dtype: float64

## Problem: dataset too centered around a specific value

In [45]:
df_index.label.describe()

count    10000.000000
mean        63.529537
std          5.500780
min         48.837187
25%         59.621903
50%         63.253673
75%         66.986460
max         90.799333
Name: label, dtype: float64

In [46]:
df_downsample = df_index.copy(deep=True)
df_downsample

g-0_p-0  g-0_p-1  g-0_p-2  g-0_p-3  g-0_p-4  g-1_p-0  g-1_p-1  g-1_p-2  \
0         264      191       98      235       35      356      253        9   
1         338      176       95       11      161      248      364       53   
2         290       99       75       21      237      287      215      213   
3          15      277       93      106      290      354       60      226   
4         190      260       34      286      360      167      251      298   
...       ...      ...      ...      ...      ...      ...      ...      ...   
9995      127       84      110      152      265       90      318       72   
9996      286       97      191      288       32      268       41      347   
9997      372      168      198      199      239      369      323      277   
9998      154      310      224       59       87      207       97       78   
9999      351       31      277      304      357       35      111      254   

      g-1_p-3  g-1_p-4  ...  g-8_p-1  g-8_p-2  g-8_p-3  g-8_p-4  g-9_p-0  \
0         147      311  ...      315      265       92       23      287   
1          64       71  ...      181      365       96      187      165   
2         172      214  ...       76      188      274       77      264   
3          75      318  ...      243      288       74      131      344   
4         256       15  ...       48      258      107        5      307   
...       ...      ...  ...      ...      ...      ...      ...      ...   
9995      331      237  ...        7      341      126       70      208   
9996      272      169  ...      178      269      310       79      370   
9997      174      281  ...      112       75      331      177      163   
9998      290      241  ...      338      254      183      145       22   
9999       40       69  ...       71       65      163      296      123   

      g-9_p-1  g-9_p-2  g-9_p-3  g-9_p-4      label  
0          17      234      223      117  68.011480  
1          38      114       98       56  55.463373  
2         117      254      168       65  66.108493  
3          86      266      218       83  58.642507  
4         121      162        7       37  62.584213  
...       ...      ...      ...      ...        ...  
9995       67      248      291      246  63.678893  
9996      108      189      340       24  55.686920  
9997      155        7      188      290  66.045467  
9998       95      247      158      231  72.811613  
9999      363      180      148      297  53.813760  

[10000 rows x 51 columns]

In [47]:
df_downsample['label_cat'] = (df_downsample.label/5).round()

In [48]:
df_downsample

g-0_p-0  g-0_p-1  g-0_p-2  g-0_p-3  g-0_p-4  g-1_p-0  g-1_p-1  g-1_p-2  \
0         264      191       98      235       35      356      253        9   
1         338      176       95       11      161      248      364       53   
2         290       99       75       21      237      287      215      213   
3          15      277       93      106      290      354       60      226   
4         190      260       34      286      360      167      251      298   
...       ...      ...      ...      ...      ...      ...      ...      ...   
9995      127       84      110      152      265       90      318       72   
9996      286       97      191      288       32      268       41      347   
9997      372      168      198      199      239      369      323      277   
9998      154      310      224       59       87      207       97       78   
9999      351       31      277      304      357       35      111      254   

      g-1_p-3  g-1_p-4  ...  g-8_p-2  g-8_p-3  g-8_p-4  g-9_p-0  g-9_p-1  \
0         147      311  ...      265       92       23      287       17   
1          64       71  ...      365       96      187      165       38   
2         172      214  ...      188      274       77      264      117   
3          75      318  ...      288       74      131      344       86   
4         256       15  ...      258      107        5      307      121   
...       ...      ...  ...      ...      ...      ...      ...      ...   
9995      331      237  ...      341      126       70      208       67   
9996      272      169  ...      269      310       79      370      108   
9997      174      281  ...       75      331      177      163      155   
9998      290      241  ...      254      183      145       22       95   
9999       40       69  ...       65      163      296      123      363   

      g-9_p-2  g-9_p-3  g-9_p-4      label  label_cat  
0         234      223      117  68.011480       14.0  
1         114       98       56  55.463373       11.0  
2         254      168       65  66.108493       13.0  
3         266      218       83  58.642507       12.0  
4         162        7       37  62.584213       13.0  
...       ...      ...      ...        ...        ...  
9995      248      291      246  63.678893       13.0  
9996      189      340       24  55.686920       11.0  
9997        7      188      290  66.045467       13.0  
9998      247      158      231  72.811613       15.0  
9999      180      148      297  53.813760       11.0  

[10000 rows x 52 columns]

In [49]:
n_samples = df_downsample.groupby('label_cat').size().min()
n_samples

1

In [54]:
downsampled_df = df_downsample.groupby('label_cat').apply(lambda x: x.sample(min(len(x), 10)))
downsampled_df

g-0_p-0  g-0_p-1  g-0_p-2  g-0_p-3  g-0_p-4  g-1_p-0  g-1_p-1  \
label_cat                                                                       
10.0      1176       81      115      135      301      163       62      110   
          3532       94      128       17      314      315      171       74   
          9139      222      334      361      356       99      101      349   
          3016      323      145       11      362      233        7      207   
          5023      204      175      365       27      138      268      197   
...                 ...      ...      ...      ...      ...      ...      ...   
17.0      2424      106        4      199      269      110       98      129   
          1733       91      101      360      134       87      188      163   
          5103      200      247      181       49      260      342      156   
          5691      231       92        3      230       81      191      314   
18.0      7641      314      150       39      307       47      114      287   

                g-1_p-2  g-1_p-3  g-1_p-4  ...  g-8_p-2  g-8_p-3  g-8_p-4  \
label_cat                                  ...                              
10.0      1176      291      349      240  ...        5      292      180   
          3532      297      197        3  ...      127      136        1   
          9139       32       85      232  ...      358      147       24   
          3016       37      156      347  ...      308      157      266   
          5023      217      187        8  ...      313      286      116   
...                 ...      ...      ...  ...      ...      ...      ...   
17.0      2424        7      203      241  ...      163      234      164   
          1733       70       26       85  ...      109       75      223   
          5103      340      227      287  ...      186       64      353   
          5691      209      124      163  ...      250       54      324   
18.0      7641       61      112      247  ...      260      232      107   

                g-9_p-0  g-9_p-1  g-9_p-2  g-9_p-3  g-9_p-4      label  \
label_cat                                                                
10.0      1176      234      114       60      304       61  51.016440   
          3532       52      167      260       21      279  50.414187   
          9139      360      216       81      247      332  49.675400   
          3016      271       89      180      219      235  50.657640   
          5023      173      145       94       98      219  50.814787   
...                 ...      ...      ...      ...      ...        ...   
17.0      2424       71       32      179      231      244  85.504837   
          1733       22      130      350       61      117  84.667533   
          5103       51      109      112       84      241  82.867680   
          5691       27      106      164      107      155  83.928683   
18.0      7641      127      102       43      188      258  90.799333   

                label_cat  
label_cat                  
10.0      1176       10.0  
          3532       10.0  
          9139       10.0  
          3016       10.0  
          5023       10.0  
...                   ...  
17.0      2424       17.0  
          1733       17.0  
          5103       17.0  
          5691       17.0  
18.0      7641       18.0  

[76 rows x 52 columns]

In [55]:
downsampled_df.label.describe()

count    76.000000
mean     66.589754
std      10.809784
min      49.675400
25%      56.299377
50%      66.096620
75%      75.225410
max      90.799333
Name: label, dtype: float64