# Preparation of Dataset (development notebook)

## Import section

In [1]:
import numpy as np
import pandas as pd

from etnn.data.prepare_ferris_wheel import prepare_1_ferris, generate_ferris_dataset, add_valid_permutations, \
    sample_new_permutations
from etnn.data.ferris_score_helpers import build_wheel_happyness
from etnn.data.ferris_wheel import load_pure_ferris_wheel_dataset, load_modified_ferris_wheel_dataset
import torch
from torch.utils.data import random_split, DataLoader
from tqdm import tqdm

In [2]:
DATASET_PATH = "../datasets"

## Person dataset

In [3]:
df_health = prepare_1_ferris(
    dataset_path="../datasets",
    df_name_output="health_dataset_preprocessed-1.csv",
    df_name_input="Sleep_health_and_lifestyle_dataset.csv",
    try_pregen=True
)

In [4]:
df_health.head()

id  age  occupation  sleep_duration  sleep_quality  physical_activity  \
0   1   27           1             6.1              6                 42   
1   2   28           2             6.2              6                 60   
2   3   28           2             6.2              6                 60   
3   4   28           3             5.9              4                 30   
4   5   28           3             5.9              4                 30   

   stress_level  bmi  heart_rate  daily_steps  sleep_disorder  \
0             6    2          77         4200               0   
1             8    0          75        10000               0   
2             8    0          75        10000               0   
3             8    3          85         3000               1   
4             8    3          85         3000               1   

   blood_pressure1  blood_pressure2  gender_male  gender_female  gender_other  
0              126               83         True          False         False  
1              125               80         True          False         False  
2              125               80         True          False         False  
3              140               90         True          False         False  
4              140               90         True          False         False

## Gondola dataset (indexing)

In [5]:
# take group of ids from persons and state how the label for this group shall be calculated

In [6]:
# define ferris wheel
num_gondolas = 10
num_part_pg = 5

In [7]:
# generate sample element
random_order = np.arange(len(df_health)) + 1
np.random.shuffle(random_order)

In [8]:
example = [
    random_order[i*num_part_pg:(i+1)*num_part_pg]
    for i in range(num_gondolas)
]

In [9]:
example

[array([289, 337,  40,   2, 252]),
 array([158, 170, 299, 181, 236]),
 array([168,  89, 219, 290, 371]),
 array([269, 343, 278, 312,  69]),
 array([ 45, 234,  61, 107,  75]),
 array([286, 347, 127, 200,  97]),
 array([328, 364, 346, 149, 315]),
 array([256, 117, 277, 229,  52]),
 array([ 57, 255, 283, 185,   1]),
 array([366, 350, 150, 211, 140])]

In [10]:
random_order[:num_gondolas*num_part_pg].reshape(num_gondolas, num_part_pg)

array([[289, 337,  40,   2, 252],
       [158, 170, 299, 181, 236],
       [168,  89, 219, 290, 371],
       [269, 343, 278, 312,  69],
       [ 45, 234,  61, 107,  75],
       [286, 347, 127, 200,  97],
       [328, 364, 346, 149, 315],
       [256, 117, 277, 229,  52],
       [ 57, 255, 283, 185,   1],
       [366, 350, 150, 211, 140]])

Rules:
- People being happy with other people in same gondola
    + Age composition too seperated is bad
    + shift in gender is bad if too much, 50-50 is good or all one gender
    + same with age composition
    + sleep derived(multiplier with quality) persons get a subtraction and 'good sleepers' get bonus (sleep disorder counts as stronger subtraction)
    + higher heart rate and pressure = joy or fear
    + composition of persons in regards to bmi : extreme values make others (no exception for group all those as to many underweight or overweight persons may be awquard as well)
- People being happy with neighboring gondolas composition
    + same age gets bonus, none gets penalty as potentially group is separated
    + gap between happyness index between self and neighbors causes it to produce a mean of only the neighbors

In [11]:
build_wheel_happyness(df_health, example)

58.839653333333345

In [12]:
build_wheel_happyness(df_health, random_order[:num_gondolas * num_part_pg].reshape(num_gondolas, num_part_pg))

58.839653333333345

In [13]:
# define dataset size
num_to_generate = 10_000
# define ferris wheel
num_gondolas = 10
num_part_pg = 5

In [14]:
df_index, df_health = generate_ferris_dataset(
    num_gondolas=num_gondolas,
    num_part_pg=num_part_pg,
    num_to_generate=num_to_generate,
    dataset_path="../datasets",
    df_intermediate_output_name="health_dataset_preprocessed-1.csv",
    df_name_input="Sleep_health_and_lifestyle_dataset.csv",
    try_pregen=True
)

100%|██████████| 10000/10000 [00:25<00:00, 397.56it/s]


In [15]:
df_index.head()

g-0_p-0  g-0_p-1  g-0_p-2  g-0_p-3  g-0_p-4  g-1_p-0  g-1_p-1  g-1_p-2  \
0      264      191       98      235       35      356      253        9   
1      338      176       95       11      161      248      364       53   
2      290       99       75       21      237      287      215      213   
3       15      277       93      106      290      354       60      226   
4      190      260       34      286      360      167      251      298   

   g-1_p-3  g-1_p-4  ...  g-8_p-1  g-8_p-2  g-8_p-3  g-8_p-4  g-9_p-0  \
0      147      311  ...      315      265       92       23      287   
1       64       71  ...      181      365       96      187      165   
2      172      214  ...       76      188      274       77      264   
3       75      318  ...      243      288       74      131      344   
4      256       15  ...       48      258      107        5      307   

   g-9_p-1  g-9_p-2  g-9_p-3  g-9_p-4      label  
0       17      234      223      117  68.011480  
1       38      114       98       56  55.463373  
2      117      254      168       65  66.108493  
3       86      266      218       83  58.642507  
4      121      162        7       37  62.584213  

[5 rows x 51 columns]

In [16]:
df_health.head()

id  age  occupation  sleep_duration  sleep_quality  physical_activity  \
0   1   27           1             6.1              6                 42   
1   2   28           2             6.2              6                 60   
2   3   28           2             6.2              6                 60   
3   4   28           3             5.9              4                 30   
4   5   28           3             5.9              4                 30   

   stress_level  bmi  heart_rate  daily_steps  sleep_disorder  \
0             6    2          77         4200               0   
1             8    0          75        10000               0   
2             8    0          75        10000               0   
3             8    3          85         3000               1   
4             8    3          85         3000               1   

   blood_pressure1  blood_pressure2  gender_male  gender_female  gender_other  
0              126               83         True          False         False  
1              125               80         True          False         False  
2              125               80         True          False         False  
3              140               90         True          False         False  
4              140               90         True          False         False

In [17]:
df_index.iloc[:, :-1]

g-0_p-0  g-0_p-1  g-0_p-2  g-0_p-3  g-0_p-4  g-1_p-0  g-1_p-1  g-1_p-2  \
0         264      191       98      235       35      356      253        9   
1         338      176       95       11      161      248      364       53   
2         290       99       75       21      237      287      215      213   
3          15      277       93      106      290      354       60      226   
4         190      260       34      286      360      167      251      298   
...       ...      ...      ...      ...      ...      ...      ...      ...   
9995      127       84      110      152      265       90      318       72   
9996      286       97      191      288       32      268       41      347   
9997      372      168      198      199      239      369      323      277   
9998      154      310      224       59       87      207       97       78   
9999      351       31      277      304      357       35      111      254   

      g-1_p-3  g-1_p-4  ...  g-8_p-0  g-8_p-1  g-8_p-2  g-8_p-3  g-8_p-4  \
0         147      311  ...      299      315      265       92       23   
1          64       71  ...      100      181      365       96      187   
2         172      214  ...      122       76      188      274       77   
3          75      318  ...      235      243      288       74      131   
4         256       15  ...       28       48      258      107        5   
...       ...      ...  ...      ...      ...      ...      ...      ...   
9995      331      237  ...      346        7      341      126       70   
9996      272      169  ...      194      178      269      310       79   
9997      174      281  ...      191      112       75      331      177   
9998      290      241  ...       12      338      254      183      145   
9999       40       69  ...       16       71       65      163      296   

      g-9_p-0  g-9_p-1  g-9_p-2  g-9_p-3  g-9_p-4  
0         287       17      234      223      117  
1         165       38      114       98       56  
2         264      117      254      168       65  
3         344       86      266      218       83  
4         307      121      162        7       37  
...       ...      ...      ...      ...      ...  
9995      208       67      248      291      246  
9996      370      108      189      340       24  
9997      163      155        7      188      290  
9998       22       95      247      158      231  
9999      123      363      180      148      297  

[10000 rows x 50 columns]

## Total dataset creation

In [18]:
dataset = load_pure_ferris_wheel_dataset(
    num_gondolas=num_gondolas,
    num_part_pg=num_part_pg,
    num_to_generate=num_to_generate,
    dataset_path="../datasets",
    df_intermediate_output_name="health_dataset_preprocessed-1.csv",
    df_name_input="Sleep_health_and_lifestyle_dataset.csv",
    try_pregen=True
)

In [19]:
dataset[0]

(tensor([[4.5000e+01, 1.1000e+01, 6.9000e+00, 7.0000e+00, 5.5000e+01, 5.0000e+00,
          2.0000e+00, 7.5000e+01, 5.5000e+03, 0.0000e+00, 1.2500e+02, 8.2000e+01,
          0.0000e+00, 1.0000e+00, 0.0000e+00],
         [4.3000e+01, 4.0000e+00, 6.7000e+00, 7.0000e+00, 4.5000e+01, 4.0000e+00,
          2.0000e+00, 6.5000e+01, 6.0000e+03, 2.0000e+00, 1.3500e+02, 9.0000e+01,
          0.0000e+00, 1.0000e+00, 0.0000e+00],
         [3.6000e+01, 7.0000e+00, 7.1000e+00, 8.0000e+00, 6.0000e+01, 4.0000e+00,
          0.0000e+00, 6.8000e+01, 7.0000e+03, 0.0000e+00, 1.1500e+02, 7.5000e+01,
          0.0000e+00, 1.0000e+00, 0.0000e+00],
         [4.4000e+01, 4.0000e+00, 6.6000e+00, 7.0000e+00, 4.5000e+01, 4.0000e+00,
          2.0000e+00, 6.5000e+01, 6.0000e+03, 2.0000e+00, 1.3500e+02, 9.0000e+01,
          0.0000e+00, 1.0000e+00, 0.0000e+00],
         [3.1000e+01, 2.0000e+00, 7.7000e+00, 7.0000e+00, 7.5000e+01, 6.0000e+00,
          0.0000e+00, 7.0000e+01, 8.0000e+03, 0.0000e+00, 1.2000e+02, 8.00

## DataLoaders

In [20]:
generator = torch.Generator().manual_seed(420)
train_ds, val_ds, test_ds = random_split(dataset, [0.7, 0.1, 0.2], generator=generator)

In [21]:
train_ds

In [22]:
train_loader = DataLoader(train_ds, batch_size=32, shuffle=True)

In [23]:
for x, y in train_loader:
    print(f"x-shape:{x.shape}, y-shape:{y.shape}")
    break

x-shape:torch.Size([32, 50, 15]), y-shape:torch.Size([32])


# Make weighted random sampler to easy distribution problems

In [51]:
df_index.label.round()

0       68.0
1       55.0
2       66.0
3       59.0
4       63.0
        ... 
9995    64.0
9996    56.0
9997    66.0
9998    73.0
9999    54.0
Name: label, Length: 10000, dtype: float64

## Specialize pure datasets

In [25]:
df_added_valid = add_valid_permutations(
    num_to_generate,
    df_index,
    num_gondolas
)

100%|██████████| 10000/10000 [00:00<00:00, 88330.15it/s]


In [26]:
df_added_valid

g-0_p-0  g-0_p-1  g-0_p-2  g-0_p-3  g-0_p-4  g-1_p-0  g-1_p-1  g-1_p-2  \
0          264      191       98      235       35      356      253        9   
1          338      176       95       11      161      248      364       53   
2          290       99       75       21      237      287      215      213   
3           15      277       93      106      290      354       60      226   
4          190      260       34      286      360      167      251      298   
...        ...      ...      ...      ...      ...      ...      ...      ...   
19995       14      204      272      195      136      217      178      137   
19996      278      282      328      303      251      265       25      243   
19997      169      160       69      298      314      234      346      350   
19998       26      358      181       46      355       83       54      366   
19999      224       77       98      244      111      285      194      309   

       g-1_p-3  g-1_p-4  ...  g-8_p-1  g-8_p-2  g-8_p-3  g-8_p-4  g-9_p-0  \
0          147      311  ...      315      265       92       23      287   
1           64       71  ...      181      365       96      187      165   
2          172      214  ...       76      188      274       77      264   
3           75      318  ...      243      288       74      131      344   
4          256       15  ...       48      258      107        5      307   
...        ...      ...  ...      ...      ...      ...      ...      ...   
19995       46      197  ...      263       94      345      248      227   
19996      199      365  ...      342      188       40       77       39   
19997      246      338  ...      173       73      277      286       70   
19998      125      155  ...      277      174       80      106      260   
19999      281       21  ...      123      328       73       62      270   

       g-9_p-1  g-9_p-2  g-9_p-3  g-9_p-4      label  
0           17      234      223      117  68.011480  
1           38      114       98       56  55.463373  
2          117      254      168       65  66.108493  
3           86      266      218       83  58.642507  
4          121      162        7       37  62.584213  
...        ...      ...      ...      ...        ...  
19995        6      102      127      301  59.765280  
19996      358       34      290      335  71.027800  
19997       17      180      118      137  71.582987  
19998      342      194      287      371  57.986000  
19999      132       87      185       23  70.065720  

[20000 rows x 51 columns]

In [27]:
dataset = load_modified_ferris_wheel_dataset(
    num_gondolas=num_gondolas,
    num_part_pg=num_part_pg,
    num_to_generate=num_to_generate,
    num_valid_to_add=num_to_generate,
    dataset_path="../datasets",
    df_intermediate_output_name="health_dataset_preprocessed-1.csv",
    df_name_input="Sleep_health_and_lifestyle_dataset.csv",
    try_pregen=True
)

100%|██████████| 1000/1000 [00:00<00:00, 88805.93it/s]


## Change regression task to classification

In [28]:
temp = df_index.label/(10*num_gondolas)*10

In [29]:
temp.round()

0       7.0
1       6.0
2       7.0
3       6.0
4       6.0
       ... 
9995    6.0
9996    6.0
9997    7.0
9998    7.0
9999    5.0
Name: label, Length: 10000, dtype: float64

## Problem: dataset too centered around a specific value

In [30]:
df_index.label.describe()

count    10000.000000
mean        63.529537
std          5.500780
min         48.837187
25%         59.621903
50%         63.253673
75%         66.986460
max         90.799333
Name: label, dtype: float64

In [31]:
df_downsample = df_index.copy(deep=True)
df_downsample

g-0_p-0  g-0_p-1  g-0_p-2  g-0_p-3  g-0_p-4  g-1_p-0  g-1_p-1  g-1_p-2  \
0         264      191       98      235       35      356      253        9   
1         338      176       95       11      161      248      364       53   
2         290       99       75       21      237      287      215      213   
3          15      277       93      106      290      354       60      226   
4         190      260       34      286      360      167      251      298   
...       ...      ...      ...      ...      ...      ...      ...      ...   
9995      127       84      110      152      265       90      318       72   
9996      286       97      191      288       32      268       41      347   
9997      372      168      198      199      239      369      323      277   
9998      154      310      224       59       87      207       97       78   
9999      351       31      277      304      357       35      111      254   

      g-1_p-3  g-1_p-4  ...  g-8_p-1  g-8_p-2  g-8_p-3  g-8_p-4  g-9_p-0  \
0         147      311  ...      315      265       92       23      287   
1          64       71  ...      181      365       96      187      165   
2         172      214  ...       76      188      274       77      264   
3          75      318  ...      243      288       74      131      344   
4         256       15  ...       48      258      107        5      307   
...       ...      ...  ...      ...      ...      ...      ...      ...   
9995      331      237  ...        7      341      126       70      208   
9996      272      169  ...      178      269      310       79      370   
9997      174      281  ...      112       75      331      177      163   
9998      290      241  ...      338      254      183      145       22   
9999       40       69  ...       71       65      163      296      123   

      g-9_p-1  g-9_p-2  g-9_p-3  g-9_p-4      label  
0          17      234      223      117  68.011480  
1          38      114       98       56  55.463373  
2         117      254      168       65  66.108493  
3          86      266      218       83  58.642507  
4         121      162        7       37  62.584213  
...       ...      ...      ...      ...        ...  
9995       67      248      291      246  63.678893  
9996      108      189      340       24  55.686920  
9997      155        7      188      290  66.045467  
9998       95      247      158      231  72.811613  
9999      363      180      148      297  53.813760  

[10000 rows x 51 columns]

In [32]:
df_downsample['label_cat'] = (df_downsample.label/5).round()

In [33]:
df_downsample

g-0_p-0  g-0_p-1  g-0_p-2  g-0_p-3  g-0_p-4  g-1_p-0  g-1_p-1  g-1_p-2  \
0         264      191       98      235       35      356      253        9   
1         338      176       95       11      161      248      364       53   
2         290       99       75       21      237      287      215      213   
3          15      277       93      106      290      354       60      226   
4         190      260       34      286      360      167      251      298   
...       ...      ...      ...      ...      ...      ...      ...      ...   
9995      127       84      110      152      265       90      318       72   
9996      286       97      191      288       32      268       41      347   
9997      372      168      198      199      239      369      323      277   
9998      154      310      224       59       87      207       97       78   
9999      351       31      277      304      357       35      111      254   

      g-1_p-3  g-1_p-4  ...  g-8_p-2  g-8_p-3  g-8_p-4  g-9_p-0  g-9_p-1  \
0         147      311  ...      265       92       23      287       17   
1          64       71  ...      365       96      187      165       38   
2         172      214  ...      188      274       77      264      117   
3          75      318  ...      288       74      131      344       86   
4         256       15  ...      258      107        5      307      121   
...       ...      ...  ...      ...      ...      ...      ...      ...   
9995      331      237  ...      341      126       70      208       67   
9996      272      169  ...      269      310       79      370      108   
9997      174      281  ...       75      331      177      163      155   
9998      290      241  ...      254      183      145       22       95   
9999       40       69  ...       65      163      296      123      363   

      g-9_p-2  g-9_p-3  g-9_p-4      label  label_cat  
0         234      223      117  68.011480       14.0  
1         114       98       56  55.463373       11.0  
2         254      168       65  66.108493       13.0  
3         266      218       83  58.642507       12.0  
4         162        7       37  62.584213       13.0  
...       ...      ...      ...        ...        ...  
9995      248      291      246  63.678893       13.0  
9996      189      340       24  55.686920       11.0  
9997        7      188      290  66.045467       13.0  
9998      247      158      231  72.811613       15.0  
9999      180      148      297  53.813760       11.0  

[10000 rows x 52 columns]

In [34]:
n_samples = df_downsample.groupby('label_cat').size().min()
n_samples

1

In [35]:
downsampled_df = df_downsample.groupby('label_cat').apply(lambda x: x.sample(min(len(x), 10)))
downsampled_df

g-0_p-0  g-0_p-1  g-0_p-2  g-0_p-3  g-0_p-4  g-1_p-0  g-1_p-1  \
label_cat                                                                       
10.0      441       160      217      281      247      172      374      194   
          4083      224      106      120      349      180      245      319   
          8442      265       99      215       95       43      362      289   
          3276       62        4      288      114       85      148      307   
          3295      154        2      207      332      351      122      245   
...                 ...      ...      ...      ...      ...      ...      ...   
17.0      5691      231       92        3      230       81      191      314   
          5103      200      247      181       49      260      342      156   
          1733       91      101      360      134       87      188      163   
          2424      106        4      199      269      110       98      129   
18.0      7641      314      150       39      307       47      114      287   

                g-1_p-2  g-1_p-3  g-1_p-4  ...  g-8_p-2  g-8_p-3  g-8_p-4  \
label_cat                                  ...                              
10.0      441       178      292        4  ...       30      242      127   
          4083      112      282       66  ...      105      134      292   
          8442      218        1       86  ...      346       68       15   
          3276      245      225      272  ...      287      137      321   
          3295      115      201      291  ...      359      116      353   
...                 ...      ...      ...  ...      ...      ...      ...   
17.0      5691      209      124      163  ...      250       54      324   
          5103      340      227      287  ...      186       64      353   
          1733       70       26       85  ...      109       75      223   
          2424        7      203      241  ...      163      234      164   
18.0      7641       61      112      247  ...      260      232      107   

                g-9_p-0  g-9_p-1  g-9_p-2  g-9_p-3  g-9_p-4      label  \
label_cat                                                                
10.0      441        36      308      323      284      146  51.661587   
          4083      149       44      305      221      346  51.281613   
          8442      295      202      256      327      170  51.331107   
          3276      279      197      274      153      189  51.027027   
          3295      238      225      157      341      298  52.423960   
...                 ...      ...      ...      ...      ...        ...   
17.0      5691       27      106      164      107      155  83.928683   
          5103       51      109      112       84      241  82.867680   
          1733       22      130      350       61      117  84.667533   
          2424       71       32      179      231      244  85.504837   
18.0      7641      127      102       43      188      258  90.799333   

                label_cat  
label_cat                  
10.0      441        10.0  
          4083       10.0  
          8442       10.0  
          3276       10.0  
          3295       10.0  
...                   ...  
17.0      5691       17.0  
          5103       17.0  
          1733       17.0  
          2424       17.0  
18.0      7641       18.0  

[76 rows x 52 columns]

In [36]:
downsampled_df.label.describe()

count    76.000000
mean     66.815619
std      10.679133
min      50.452533
25%      57.122147
50%      67.005967
75%      75.684110
max      90.799333
Name: label, dtype: float64

# Generate complete dataset

In [37]:
from itertools import permutations

In [38]:
list(permutations(range(3), 2))

[(0, 1), (0, 2), (1, 0), (1, 2), (2, 0), (2, 1)]

In [39]:
num_gondolas = 10
num_part_pg = 5

In [40]:
n_persons = 374

In [41]:
# create all combinations
all_perms = permutations(range(1, n_persons + 1), num_gondolas*num_part_pg)

Wait... way too large! this has over 10^89 possibilities - scrap this

# Generation of testset

In [42]:
# idea: want to generate elements that are valid permutations and are not in the training set

In [43]:
df_index

g-0_p-0  g-0_p-1  g-0_p-2  g-0_p-3  g-0_p-4  g-1_p-0  g-1_p-1  g-1_p-2  \
0         264      191       98      235       35      356      253        9   
1         338      176       95       11      161      248      364       53   
2         290       99       75       21      237      287      215      213   
3          15      277       93      106      290      354       60      226   
4         190      260       34      286      360      167      251      298   
...       ...      ...      ...      ...      ...      ...      ...      ...   
9995      127       84      110      152      265       90      318       72   
9996      286       97      191      288       32      268       41      347   
9997      372      168      198      199      239      369      323      277   
9998      154      310      224       59       87      207       97       78   
9999      351       31      277      304      357       35      111      254   

      g-1_p-3  g-1_p-4  ...  g-8_p-1  g-8_p-2  g-8_p-3  g-8_p-4  g-9_p-0  \
0         147      311  ...      315      265       92       23      287   
1          64       71  ...      181      365       96      187      165   
2         172      214  ...       76      188      274       77      264   
3          75      318  ...      243      288       74      131      344   
4         256       15  ...       48      258      107        5      307   
...       ...      ...  ...      ...      ...      ...      ...      ...   
9995      331      237  ...        7      341      126       70      208   
9996      272      169  ...      178      269      310       79      370   
9997      174      281  ...      112       75      331      177      163   
9998      290      241  ...      338      254      183      145       22   
9999       40       69  ...       71       65      163      296      123   

      g-9_p-1  g-9_p-2  g-9_p-3  g-9_p-4      label  
0          17      234      223      117  68.011480  
1          38      114       98       56  55.463373  
2         117      254      168       65  66.108493  
3          86      266      218       83  58.642507  
4         121      162        7       37  62.584213  
...       ...      ...      ...      ...        ...  
9995       67      248      291      246  63.678893  
9996      108      189      340       24  55.686920  
9997      155        7      188      290  66.045467  
9998       95      247      158      231  72.811613  
9999      363      180      148      297  53.813760  

[10000 rows x 51 columns]

In [44]:
df_test = sample_new_permutations(
    df_index=df_index,
    num_gondolas=num_gondolas,
    num_elem=10,
    merge_check=True
)

100%|██████████| 10/10 [00:00<?, ?it/s]


In [45]:
df_test

g-0_p-0  g-0_p-1  g-0_p-2  g-0_p-3  g-0_p-4  g-1_p-0  g-1_p-1  g-1_p-2  \
0      271      133      330       40      368      249      272      315   
1       35      105      304      184       80      168      247       25   
2      349      332      209      139      169       68      282       86   
3      368      200      329      104      242       70      269        4   
4      133      288       55      307      249      331      341       98   
5       56      177      279       85       27       79      333       16   
6      106       56      150      315      240      109      129      300   
7      115      153      139      105      306      102      370      337   
8       99      271      150       61       93      141      297      284   
9      291       75      231       36      314      351      344      250   

   g-1_p-3  g-1_p-4  ...  g-8_p-1  g-8_p-2  g-8_p-3  g-8_p-4  g-9_p-0  \
0      346      362  ...      369       32      294      273      313   
1      234      279  ...      255      365      372      364      147   
2      238      233  ...       46      268      254      231      364   
3       94      163  ...      302       27      191      208       83   
4      147      324  ...      101      308      170      130      241   
5      118      197  ...       97      190      206      318      238   
6      154      310  ...      344       39      362      239      340   
7      182      242  ...       64       14      290      292      239   
8      240       70  ...      304      149      177        6      143   
9       38      114  ...      286       13      143      301      303   

   g-9_p-1  g-9_p-2  g-9_p-3  g-9_p-4      label  
0      145      298      120       49  53.943533  
1       30      153      289      316  65.757280  
2      363      176      224      270  65.431160  
3      170       73      330       63  58.608813  
4      112      154      340       37  56.869907  
5      344      252      287        1  64.406267  
6      185      320      364      207  65.462013  
7      258       18      183      194  63.058440  
8      235      294      154       50  60.430600  
9       60      121        7       61  65.278547  

[10 rows x 51 columns]

In [46]:
df_test2 = df_index.iloc[-10:]
df_test2

g-0_p-0  g-0_p-1  g-0_p-2  g-0_p-3  g-0_p-4  g-1_p-0  g-1_p-1  g-1_p-2  \
9990      106       45      228      126      234      246       89      105   
9991      324       53      301      257       20       48      316       73   
9992      284      346      238      179       80       22      190      123   
9993      123      261      272      361       15        8      346       89   
9994      146       13       58      171       90        4       24       31   
9995      127       84      110      152      265       90      318       72   
9996      286       97      191      288       32      268       41      347   
9997      372      168      198      199      239      369      323      277   
9998      154      310      224       59       87      207       97       78   
9999      351       31      277      304      357       35      111      254   

      g-1_p-3  g-1_p-4  ...  g-8_p-1  g-8_p-2  g-8_p-3  g-8_p-4  g-9_p-0  \
9990      243      344  ...      130       87      167      310      217   
9991      319      184  ...      138      195      237       11        7   
9992       17      242  ...       71      265      347      186      191   
9993      281      242  ...       99      371       32      144       55   
9994      187      185  ...       86      205      244      196      222   
9995      331      237  ...        7      341      126       70      208   
9996      272      169  ...      178      269      310       79      370   
9997      174      281  ...      112       75      331      177      163   
9998      290      241  ...      338      254      183      145       22   
9999       40       69  ...       71       65      163      296      123   

      g-9_p-1  g-9_p-2  g-9_p-3  g-9_p-4      label  
9990      146       21       54      317  61.771467  
9991      291      221      249      272  62.655867  
9992       37       78      234      320  64.899493  
9993      178       60       17      319  57.060120  
9994       29      295      199      137  59.295680  
9995       67      248      291      246  63.678893  
9996      108      189      340       24  55.686920  
9997      155        7      188      290  66.045467  
9998       95      247      158      231  72.811613  
9999      363      180      148      297  53.813760  

[10 rows x 51 columns]

In [47]:
merged = df_test2.merge(df_index, how='left', indicator=True)

In [48]:
merged

g-0_p-0  g-0_p-1  g-0_p-2  g-0_p-3  g-0_p-4  g-1_p-0  g-1_p-1  g-1_p-2  \
0      106       45      228      126      234      246       89      105   
1      324       53      301      257       20       48      316       73   
2      284      346      238      179       80       22      190      123   
3      123      261      272      361       15        8      346       89   
4      146       13       58      171       90        4       24       31   
5      127       84      110      152      265       90      318       72   
6      286       97      191      288       32      268       41      347   
7      372      168      198      199      239      369      323      277   
8      154      310      224       59       87      207       97       78   
9      351       31      277      304      357       35      111      254   

   g-1_p-3  g-1_p-4  ...  g-8_p-2  g-8_p-3  g-8_p-4  g-9_p-0  g-9_p-1  \
0      243      344  ...       87      167      310      217      146   
1      319      184  ...      195      237       11        7      291   
2       17      242  ...      265      347      186      191       37   
3      281      242  ...      371       32      144       55      178   
4      187      185  ...      205      244      196      222       29   
5      331      237  ...      341      126       70      208       67   
6      272      169  ...      269      310       79      370      108   
7      174      281  ...       75      331      177      163      155   
8      290      241  ...      254      183      145       22       95   
9       40       69  ...       65      163      296      123      363   

   g-9_p-2  g-9_p-3  g-9_p-4      label  _merge  
0       21       54      317  61.771467    both  
1      221      249      272  62.655867    both  
2       78      234      320  64.899493    both  
3       60       17      319  57.060120    both  
4      295      199      137  59.295680    both  
5      248      291      246  63.678893    both  
6      189      340       24  55.686920    both  
7        7      188      290  66.045467    both  
8      247      158      231  72.811613    both  
9      180      148      297  53.813760    both  

[10 rows x 52 columns]

In [49]:
sum(merged['_merge'] == 'both')

10

In [50]:
merged._merge

0    both
1    both
2    both
3    both
4    both
5    both
6    both
7    both
8    both
9    both
Name: _merge, dtype: category
Categories (3, object): ['left_only', 'right_only', 'both']