# Preparation of Dataset (development notebook)

## Import section

In [1]:
import numpy as np
import pandas as pd

from etnn.data.prepare_ferris_wheel import prepare_1_ferris, generate_ferris_dataset, add_valid_permutations
from etnn.data.ferris_score_helpers import build_wheel_happyness
from etnn.data.ferris_wheel import load_pure_ferris_wheel_dataset
import torch
from torch.utils.data import random_split, DataLoader
from tqdm import tqdm

In [2]:
DATASET_PATH = "../datasets"

## Person dataset

In [3]:
df_health = prepare_1_ferris(
    dataset_path="../datasets",
    df_name_output="health_dataset_preprocessed-1.csv",
    df_name_input="Sleep_health_and_lifestyle_dataset.csv",
    try_pregen=True
)

In [4]:
df_health.head()

id  age  occupation  sleep_duration  sleep_quality  physical_activity  \
0   1   27           1             6.1              6                 42   
1   2   28           2             6.2              6                 60   
2   3   28           2             6.2              6                 60   
3   4   28           3             5.9              4                 30   
4   5   28           3             5.9              4                 30   

   stress_level  bmi  heart_rate  daily_steps  sleep_disorder  \
0             6    2          77         4200               0   
1             8    0          75        10000               0   
2             8    0          75        10000               0   
3             8    3          85         3000               1   
4             8    3          85         3000               1   

   blood_pressure1  blood_pressure2  gender_male  gender_female  gender_other  
0              126               83         True          False         False  
1              125               80         True          False         False  
2              125               80         True          False         False  
3              140               90         True          False         False  
4              140               90         True          False         False

## Gondola dataset (indexing)

In [5]:
# take group of ids from persons and state how the label for this group shall be calculated

In [6]:
# define ferris wheel
num_gondolas = 10
num_part_pg = 5

In [7]:
# generate sample element
random_order = np.arange(len(df_health)) + 1
np.random.shuffle(random_order)

In [8]:
example = [
    random_order[i*num_part_pg:(i+1)*num_part_pg]
    for i in range(num_gondolas)
]

In [9]:
example

[array([260, 247, 207,  73, 206]),
 array([228, 239, 130, 136, 341]),
 array([264, 295, 101, 174, 336]),
 array([334,  44,  30, 301, 122]),
 array([210,  47,   5, 218,  72]),
 array([185, 111, 102, 317,  15]),
 array([131, 182, 116, 370, 104]),
 array([251, 263, 314, 162,  69]),
 array([241,   1, 242, 358, 292]),
 array([146,  66, 138, 219, 110])]

In [10]:
random_order[:num_gondolas*num_part_pg].reshape(num_gondolas, num_part_pg)

array([[260, 247, 207,  73, 206],
       [228, 239, 130, 136, 341],
       [264, 295, 101, 174, 336],
       [334,  44,  30, 301, 122],
       [210,  47,   5, 218,  72],
       [185, 111, 102, 317,  15],
       [131, 182, 116, 370, 104],
       [251, 263, 314, 162,  69],
       [241,   1, 242, 358, 292],
       [146,  66, 138, 219, 110]])

Rules:
- People being happy with other people in same gondola
    + Age composition too seperated is bad
    + shift in gender is bad if too much, 50-50 is good or all one gender
    + same with age composition
    + sleep derived(multiplier with quality) persons get a subtraction and 'good sleepers' get bonus (sleep disorder counts as stronger subtraction)
    + higher heart rate and pressure = joy or fear
    + composition of persons in regards to bmi : extreme values make others (no exception for group all those as to many underweight or overweight persons may be awquard as well)
- People being happy with neighboring gondolas composition
    + same age gets bonus, none gets penalty as potentially group is separated
    + gap between happyness index between self and neighbors causes it to produce a mean of only the neighbors

In [11]:
build_wheel_happyness(df_health, example)

64.98157333333333

In [12]:
build_wheel_happyness(df_health, random_order[:num_gondolas * num_part_pg].reshape(num_gondolas, num_part_pg))

64.98157333333333

In [13]:
# define dataset size
num_to_generate = 10_000
# define ferris wheel
num_gondolas = 10
num_part_pg = 5

In [14]:
df_index, df_health = generate_ferris_dataset(
    num_gondolas=num_gondolas,
    num_part_pg=num_part_pg,
    num_to_generate=num_to_generate,
    dataset_path="../datasets",
    df_intermediate_output_name="health_dataset_preprocessed-1.csv",
    df_name_input="Sleep_health_and_lifestyle_dataset.csv",
    try_pregen=True
)

In [15]:
df_index.head()

g-0_p-0  g-0_p-1  g-0_p-2  g-0_p-3  g-0_p-4  g-1_p-0  g-1_p-1  g-1_p-2  \
0      264      191       98      235       35      356      253        9   
1      338      176       95       11      161      248      364       53   
2      290       99       75       21      237      287      215      213   
3       15      277       93      106      290      354       60      226   
4      190      260       34      286      360      167      251      298   

   g-1_p-3  g-1_p-4  ...  g-8_p-1  g-8_p-2  g-8_p-3  g-8_p-4  g-9_p-0  \
0      147      311  ...      315      265       92       23      287   
1       64       71  ...      181      365       96      187      165   
2      172      214  ...       76      188      274       77      264   
3       75      318  ...      243      288       74      131      344   
4      256       15  ...       48      258      107        5      307   

   g-9_p-1  g-9_p-2  g-9_p-3  g-9_p-4      label  
0       17      234      223      117  68.011480  
1       38      114       98       56  55.463373  
2      117      254      168       65  66.108493  
3       86      266      218       83  58.642507  
4      121      162        7       37  62.584213  

[5 rows x 51 columns]

In [16]:
df_health.head()

id  age  occupation  sleep_duration  sleep_quality  physical_activity  \
0   1   27           1             6.1              6                 42   
1   2   28           2             6.2              6                 60   
2   3   28           2             6.2              6                 60   
3   4   28           3             5.9              4                 30   
4   5   28           3             5.9              4                 30   

   stress_level  bmi  heart_rate  daily_steps  sleep_disorder  \
0             6    2          77         4200               0   
1             8    0          75        10000               0   
2             8    0          75        10000               0   
3             8    3          85         3000               1   
4             8    3          85         3000               1   

   blood_pressure1  blood_pressure2  gender_male  gender_female  gender_other  
0              126               83         True          False         False  
1              125               80         True          False         False  
2              125               80         True          False         False  
3              140               90         True          False         False  
4              140               90         True          False         False

In [17]:
df_index.iloc[:, :-1]

g-0_p-0  g-0_p-1  g-0_p-2  g-0_p-3  g-0_p-4  g-1_p-0  g-1_p-1  g-1_p-2  \
0         264      191       98      235       35      356      253        9   
1         338      176       95       11      161      248      364       53   
2         290       99       75       21      237      287      215      213   
3          15      277       93      106      290      354       60      226   
4         190      260       34      286      360      167      251      298   
...       ...      ...      ...      ...      ...      ...      ...      ...   
9995      127       84      110      152      265       90      318       72   
9996      286       97      191      288       32      268       41      347   
9997      372      168      198      199      239      369      323      277   
9998      154      310      224       59       87      207       97       78   
9999      351       31      277      304      357       35      111      254   

      g-1_p-3  g-1_p-4  ...  g-8_p-0  g-8_p-1  g-8_p-2  g-8_p-3  g-8_p-4  \
0         147      311  ...      299      315      265       92       23   
1          64       71  ...      100      181      365       96      187   
2         172      214  ...      122       76      188      274       77   
3          75      318  ...      235      243      288       74      131   
4         256       15  ...       28       48      258      107        5   
...       ...      ...  ...      ...      ...      ...      ...      ...   
9995      331      237  ...      346        7      341      126       70   
9996      272      169  ...      194      178      269      310       79   
9997      174      281  ...      191      112       75      331      177   
9998      290      241  ...       12      338      254      183      145   
9999       40       69  ...       16       71       65      163      296   

      g-9_p-0  g-9_p-1  g-9_p-2  g-9_p-3  g-9_p-4  
0         287       17      234      223      117  
1         165       38      114       98       56  
2         264      117      254      168       65  
3         344       86      266      218       83  
4         307      121      162        7       37  
...       ...      ...      ...      ...      ...  
9995      208       67      248      291      246  
9996      370      108      189      340       24  
9997      163      155        7      188      290  
9998       22       95      247      158      231  
9999      123      363      180      148      297  

[10000 rows x 50 columns]

## Total dataset creation

In [18]:
dataset = load_pure_ferris_wheel_dataset(
    num_gondolas=num_gondolas,
    num_part_pg=num_part_pg,
    num_to_generate=num_to_generate,
    dataset_path="../datasets",
    df_intermediate_output_name="health_dataset_preprocessed-1.csv",
    df_name_input="Sleep_health_and_lifestyle_dataset.csv",
    try_pregen=True
)

In [19]:
dataset[0]

(tensor([[4.5000e+01, 1.1000e+01, 6.9000e+00, 7.0000e+00, 5.5000e+01, 5.0000e+00,
          2.0000e+00, 7.5000e+01, 5.5000e+03, 0.0000e+00, 1.2500e+02, 8.2000e+01,
          0.0000e+00, 1.0000e+00, 0.0000e+00],
         [4.3000e+01, 4.0000e+00, 6.7000e+00, 7.0000e+00, 4.5000e+01, 4.0000e+00,
          2.0000e+00, 6.5000e+01, 6.0000e+03, 2.0000e+00, 1.3500e+02, 9.0000e+01,
          0.0000e+00, 1.0000e+00, 0.0000e+00],
         [3.6000e+01, 7.0000e+00, 7.1000e+00, 8.0000e+00, 6.0000e+01, 4.0000e+00,
          0.0000e+00, 6.8000e+01, 7.0000e+03, 0.0000e+00, 1.1500e+02, 7.5000e+01,
          0.0000e+00, 1.0000e+00, 0.0000e+00],
         [4.4000e+01, 4.0000e+00, 6.6000e+00, 7.0000e+00, 4.5000e+01, 4.0000e+00,
          2.0000e+00, 6.5000e+01, 6.0000e+03, 2.0000e+00, 1.3500e+02, 9.0000e+01,
          0.0000e+00, 1.0000e+00, 0.0000e+00],
         [3.1000e+01, 2.0000e+00, 7.7000e+00, 7.0000e+00, 7.5000e+01, 6.0000e+00,
          0.0000e+00, 7.0000e+01, 8.0000e+03, 0.0000e+00, 1.2000e+02, 8.00

## DataLoaders

In [20]:
generator = torch.Generator().manual_seed(420)
train_ds, val_ds, test_ds = random_split(dataset, [0.7, 0.1, 0.2], generator=generator)

In [21]:
train_ds

In [22]:
train_loader = DataLoader(train_ds, batch_size=32, shuffle=True)

In [23]:
for x, y in train_loader:
    print(f"x-shape:{x.shape}, y-shape:{y.shape}")
    break

x-shape:torch.Size([32, 50, 15]), y-shape:torch.Size([32])


## Specialize pure datasets

In [24]:
df_added_valid = add_valid_permutations(
    num_to_generate,
    df_index,
    num_gondolas
)

100%|██████████| 10000/10000 [00:00<00:00, 82646.87it/s]


In [25]:
df_added_valid

g-0_p-0  g-0_p-1  g-0_p-2  g-0_p-3  g-0_p-4  g-1_p-0  g-1_p-1  g-1_p-2  \
0        264.0    191.0     98.0    235.0     35.0    356.0    253.0      9.0   
1        338.0    176.0     95.0     11.0    161.0    248.0    364.0     53.0   
2        290.0     99.0     75.0     21.0    237.0    287.0    215.0    213.0   
3         15.0    277.0     93.0    106.0    290.0    354.0     60.0    226.0   
4        190.0    260.0     34.0    286.0    360.0    167.0    251.0    298.0   
...        ...      ...      ...      ...      ...      ...      ...      ...   
19995    192.0     99.0    111.0    355.0    130.0    230.0     43.0     87.0   
19996      3.0     10.0    288.0    281.0    101.0    118.0    228.0     69.0   
19997     24.0    116.0    280.0     69.0    207.0    151.0     32.0    308.0   
19998      4.0    119.0    160.0     35.0    318.0    209.0    204.0     92.0   
19999     59.0    107.0    290.0    331.0    319.0    126.0    247.0    344.0   

       g-1_p-3  g-1_p-4  ...  g-8_p-1  g-8_p-2  g-8_p-3  g-8_p-4  g-9_p-0  \
0        147.0    311.0  ...    315.0    265.0     92.0     23.0    287.0   
1         64.0     71.0  ...    181.0    365.0     96.0    187.0    165.0   
2        172.0    214.0  ...     76.0    188.0    274.0     77.0    264.0   
3         75.0    318.0  ...    243.0    288.0     74.0    131.0    344.0   
4        256.0     15.0  ...     48.0    258.0    107.0      5.0    307.0   
...        ...      ...  ...      ...      ...      ...      ...      ...   
19995     44.0     17.0  ...    228.0    185.0    160.0    278.0    324.0   
19996    311.0     28.0  ...    310.0    356.0     84.0    216.0     25.0   
19997    293.0    159.0  ...     40.0    285.0     94.0    234.0     11.0   
19998    191.0      1.0  ...    342.0     58.0    367.0    306.0    270.0   
19999    160.0    224.0  ...    197.0    289.0     20.0    258.0     68.0   

       g-9_p-1  g-9_p-2  g-9_p-3  g-9_p-4      label  
0         17.0    234.0    223.0    117.0  68.011480  
1         38.0    114.0     98.0     56.0  55.463373  
2        117.0    254.0    168.0     65.0  66.108493  
3         86.0    266.0    218.0     83.0  58.642507  
4        121.0    162.0      7.0     37.0  62.584213  
...        ...      ...      ...      ...        ...  
19995    341.0    251.0    304.0    339.0  67.306093  
19996    164.0     75.0    289.0    245.0  64.498840  
19997    165.0    351.0    333.0    175.0  65.748787  
19998    109.0    341.0    161.0    373.0  61.697907  
19999    136.0    253.0    225.0    273.0  59.530067  

[20000 rows x 51 columns]