In [18]:
import pandas as pd
import numpy as np
import os
from etnn.data.prepare_ferris_wheel import prepare_1_ferris
from etnn.data.ferris_score_helpers import build_wheel_happyness

In [2]:
df = prepare_1_ferris(
    dataset_path=".",
    df_name_output="health_dataset_preprocessed-1.csv",
    df_name_input="Sleep_health_and_lifestyle_dataset.csv",
    try_pregen=True
)

In [3]:
df.head()

id  age  occupation  sleep_duration  sleep_quality  physical_activity  \
0   1   27           1             6.1              6                 42   
1   2   28           2             6.2              6                 60   
2   3   28           2             6.2              6                 60   
3   4   28           3             5.9              4                 30   
4   5   28           3             5.9              4                 30   

   stress_level  bmi  heart_rate  daily_steps  sleep_disorder  \
0             6    2          77         4200               0   
1             8    0          75        10000               0   
2             8    0          75        10000               0   
3             8    3          85         3000               1   
4             8    3          85         3000               1   

   blood_pressure1  blood_pressure2  gender_male  gender_female  gender_other  
0              126               83         True          False         False  
1              125               80         True          False         False  
2              125               80         True          False         False  
3              140               90         True          False         False  
4              140               90         True          False         False

In [4]:
# take group of ids from persons and state how the label for this group shall be calculated

In [5]:
# define ferris wheel
num_gondolas = 10
num_part_pg = 5

In [6]:
# generate sample element
random_order = np.arange(len(df))+1
np.random.shuffle(random_order)

In [7]:
example = [
    random_order[i*num_part_pg:(i+1)*num_part_pg]
    for i in range(num_gondolas)
]

In [8]:
example

[array([ 53, 331, 367, 229, 248]),
 array([192, 179,  92, 199, 258]),
 array([213, 197, 174, 158,  72]),
 array([ 38, 147, 290, 165,  41]),
 array([339, 146, 134, 283,  95]),
 array([190, 171, 113, 268, 247]),
 array([266,  37,  78, 310,  75]),
 array([334, 116, 284, 340,  97]),
 array([250, 177, 256, 299,  33]),
 array([161, 245, 209, 234, 132])]

Rules:
- People being happy with other people in same gondola
    + Age composition too seperated is bad
    + shift in gender is bad if too much, 50-50 is good or all one gender
    + same with age composition
    + sleep derived(multiplier with quality) persons get a subtraction and 'good sleepers' get bonus (sleep disorder counts as stronger subtraction)
    + higher heart rate and pressure = joy or fear
    + composition of persons in regards to bmi : extreme values make others (no exception for group all those as to many underweight or overweight persons may be awquard as well)
- People being happy with neighboring gondolas composition
    + same age gets bonus, none gets penalty as potentially group is separated
    + gap between happyness index between self and neighbors causes it to produce a mean of only the neighbors

In [19]:
build_wheel_happyness(df, example)

69.25677333333333